export const CONTACTS_TOOLS = [
  { name: 'contacts_list', description: 'list contacts from Google Contacts', inputSchema: { type: 'object', properties: { page_size: { type: 'number', description: 'max contacts default 100', default: 100 }, page_token: { type: 'string', description: 'pagination token' }, sort_order: { type: 'string', enum: ['LAST_MODIFIED_ASCENDING', 'LAST_MODIFIED_DESCENDING', 'FIRST_NAME_ASCENDING', 'LAST_NAME_ASCENDING'] } } } },
  { name: 'contacts_get', description: 'get a contact by resource name', inputSchema: { type: 'object', properties: { resource_name: { type: 'string', description: 'contact resource name eg people/c123' } }, required: ['resource_name'] } },
  { name: 'contacts_search', description: 'search contacts by name email or phone', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'search query' }, page_size: { type: 'number', description: 'max results default 30', default: 30 } }, required: ['query'] } },
  { name: 'contacts_manage', description: 'create update or delete a contact', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['create', 'update', 'delete'], description: 'action to perform' }, resource_name: { type: 'string', description: 'contact resource name for update delete' }, given_name: { type: 'string', description: 'first name' }, family_name: { type: 'string', description: 'last name' }, emails: { type: 'array', items: { type: 'string' }, description: 'email addresses' }, phones: { type: 'array', items: { type: 'string' }, description: 'phone numbers' }, organization: { type: 'string', description: 'company name' } }, required: ['action'] } },
  { name: 'contacts_list_groups', description: 'list contact groups', inputSchema: { type: 'object', properties: { page_size: { type: 'number', default: 200 } } } },
  { name: 'contacts_get_group', description: 'get a contact group by resource name', inputSchema: { type: 'object', properties: { resource_name: { type: 'string', description: 'group resource name' } }, required: ['resource_name'] } },
  { name: 'contacts_batch', description: 'add or remove contacts from a group', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['add_to_group', 'remove_from_group'], description: 'batch action' }, resource_names: { type: 'array', items: { type: 'string' }, description: 'contact resource names' }, group_resource_name: { type: 'string', description: 'group resource name' } }, required: ['action', 'resource_names', 'group_resource_name'] } },
  { name: 'contacts_manage_group', description: 'create update or delete a contact group', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['create', 'update', 'delete'], description: 'action to perform' }, resource_name: { type: 'string', description: 'group resource name for update delete' }, name: { type: 'string', description: 'group name' } }, required: ['action'] } }
];
