export const loginHtml = (authUrl, sessionId) =>
  `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>docmcp - Login</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;display:flex;justify-content:center;align-items:center;padding:20px}.container{background:#fff;border-radius:20px;padding:40px;box-shadow:0 20px 40px rgba(0,0,0,0.1);max-width:500px;width:100%;text-align:center}.logo{font-size:48px;font-weight:bold;color:#667eea;margin-bottom:20px}.title{font-size:28px;color:#333;margin-bottom:30px}.google-login-button{background:#4285F4;color:#fff;border:none;padding:15px 30px;font-size:16px;font-weight:bold;border-radius:8px;cursor:pointer;transition:all 0.3s;display:inline-flex;align-items:center;gap:10px;text-decoration:none}.google-login-button:hover{background:#3367D6;transform:translateY(-2px);box-shadow:0 5px 15px rgba(66,133,244,0.4)}.session-info{margin-top:30px;padding:20px;background:#f5f7fa;border-radius:10px;font-size:14px;color:#555}.session-info code{background:#e8e8e8;padding:2px 6px;border-radius:4px;font-family:monospace;font-size:12px}@media(max-width:600px){.container{padding:30px 20px}.title{font-size:24px}}</style></head><body><div class="container"><div class="logo">📄</div><h1 class="title">docmcp</h1><p>Connect Google Workspace to use MCP tools</p><a href="${authUrl}" class="google-login-button"><span>🔐</span>Sign in with Google</a><div class="session-info"><p><strong>Session:</strong> <code>${sessionId}</code></p></div></div></body></html>`;

export const errorHtml = (title, subtitle, error = '') =>
  `<!DOCTYPE html><html><head><title>${title}</title><style>body{font-family:sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;display:flex;justify-content:center;align-items:center;padding:20px}.container{background:#fff;border-radius:20px;padding:40px;box-shadow:0 20px 40px rgba(0,0,0,0.1);max-width:500px;text-align:center}.error-icon{font-size:80px;margin-bottom:20px}.title{font-size:28px;color:#333;margin-bottom:10px}.subtitle{font-size:16px;color:#666;margin-bottom:30px}.back-button{background:#667eea;color:#fff;border:none;padding:15px 30px;border-radius:8px;cursor:pointer;text-decoration:none;display:inline-block}</style></head><body><div class="container"><div class="error-icon">❌</div><h1 class="title">${title}</h1><p class="subtitle">${subtitle}</p>${error ? `<pre>${error}</pre>` : ''}<a href="/login" class="back-button">Try Again</a></div></body></html>`;

export const successHtml = (sessionId, baseUrl) => {
  const mcpUrl = `${baseUrl}/mcp`;
  const mcpTokenUrl = `${baseUrl}/mcp?token=${sessionId}`;
  return `<!DOCTYPE html><html><head><title>docmcp - Authenticated</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;display:flex;justify-content:center;align-items:center;padding:20px}.container{background:#fff;border-radius:20px;padding:40px;box-shadow:0 20px 40px rgba(0,0,0,0.1);max-width:600px;width:100%;text-align:center}.success-icon{font-size:64px;margin-bottom:20px}.title{font-size:28px;color:#333;margin-bottom:10px}.token-box{background:#f0f4ff;border:2px solid #667eea;border-radius:12px;padding:20px;margin:20px 0;text-align:left}.token-val{font-family:monospace;font-size:13px;color:#333;background:#fff;border:1px solid #ddd;border-radius:6px;padding:10px;word-break:break-all;cursor:pointer;user-select:all}.copy-btn{background:#667eea;color:#fff;border:none;padding:10px 20px;border-radius:6px;cursor:pointer;font-size:14px;margin-top:10px;width:100%}.steps{background:#f9f9f9;border-radius:12px;padding:20px;margin:20px 0;text-align:left}.steps ol{padding-left:18px}.steps li{font-size:14px;color:#555;padding:5px 0}.mcp-btn{display:inline-block;background:#4CAF50;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:bold;margin-top:10px}</style></head><body><div class="container"><div class="success-icon">✅</div><h1 class="title">Authenticated!</h1><p>Your Google account is connected.</p><div class="token-box"><label>API Token</label><div class="token-val" id="sid">${sessionId}</div><button class="copy-btn" onclick="copy('sid',this)">Copy Token</button></div><div class="steps"><h3>ChatGPT Setup</h3><ol><li>Enable Developer Mode in Settings</li><li>Create new app, MCP URL: <code>${mcpUrl}</code></li><li>Choose OAuth, sign in when prompted</li></ol></div><a href="/mcp?token=${sessionId}" class="mcp-btn">Test Connection</a></div><script>function copy(id,btn){navigator.clipboard.writeText(document.getElementById(id).textContent.trim()).then(()=>{btn.textContent='Copied!';setTimeout(()=>btn.textContent='Copy Token',2000)})}</script></body></html>`;
};
